baseURL = "http://localhost:1313/"
languageCode = "fr-ca"
title = "Portfolio"
theme = "PaperMod"
canonifyURLs = true
relativeURLs = false

[params]
  ShowBreadCrumbs = true
  ShowShareButtons = false
  ShowReadingTime = false
  mainSections = []

[menu]
  [[menu.main]]
    name = "Projets"
    identifier = "projets"
    pageRef = "/projets"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableHTML = true
  disableJS = true