baseURL = "/"
languageCode = "fr-ca"
title = "Portfolio"
theme = "PaperMod"

canonifyURLs = true
relativeURLs = false

[params]
  ShowBreadCrumbs = true          # Afficher le fil d'Ariane
  ShowShareButtons = false
  ShowReadingTime = false
  mainSections = []
  UseHugoToc = true

[languages.fr-ca]
  languageName = "Français"
  weight = 1

  [[languages.fr-ca.menu.main]]
    name = "Projets"
    pageRef = "projets"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableHTML = true
  disableJS = true