baseURL = "/"
languageCode = "fr-ca"
title = "Portfolio"
theme = "PaperMod"

[params]
  ShowBreadCrumbs = true
  ShowShareButtons = false
  ShowReadingTime = false
  mainSections = []
  disableSpecial1stPost = true # Requis pour éviter les erreurs de commit sur Github Pages
  disableJSONLD = true # Idem que ci-dessus

[menu]
  [[menu.main]]
    name = "Projets"
    url = "/projets/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true